# Generated by Django 5.2.5 on 2025-08-07 23:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='A descriptive name for the template (e.g., "Carcass Label").', max_length=100, unique=True)),
                ('template_data', models.JSONField(help_text='Stores the layout and content variables for the label (e.g., position of text, barcodes, images).')),
                ('target_item_type', models.CharField(choices=[('carcass', 'Carcass'), ('meat_cut', 'Meat Cut'), ('offal', 'Offal'), ('by_product', 'By-Product')], help_text='Specifies which type of inventory item this template is for.', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_type', models.CharField(choices=[('carcass', 'Carcass'), ('meat_cut', 'Meat Cut'), ('offal', 'Offal'), ('by_product', 'By-Product')], help_text='The type of item being labeled.', max_length=50)),
                ('item_id', models.UUIDField(help_text='The ID of the specific inventory item being labeled.')),
                ('quantity', models.IntegerField(default=1, help_text='Number of labels printed for this job.')),
                ('print_date', models.DateTimeField(auto_now_add=True, help_text='When the print job was initiated.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of the print job.', max_length=20)),
                ('label_template', models.ForeignKey(blank=True, help_text='The template used for this print job.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='labeling.labeltemplate')),
                ('printed_by', models.ForeignKey(blank=True, help_text='The user who initiated the print job.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
