# Generated by Django 5.2.5 on 2025-08-09 00:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label_code', models.CharField(help_text='A unique code printed on the label (e.g., QR code, barcode).', max_length=100, unique=True)),
                ('item_type', models.CharField(choices=[('carcass', 'Carcass'), ('meat_cut', 'Meat Cut'), ('offal', 'Offal'), ('by_product', 'By-Product')], help_text='Specifies what the label is for.', max_length=50)),
                ('item_id', models.UUIDField(help_text='The ID of the associated inventory item (e.g., Carcass.id, MeatCut.id).')),
                ('print_date', models.DateTimeField(auto_now_add=True, help_text='When the label was printed.')),
                ('printed_by', models.ForeignKey(blank=True, help_text='The user who printed the label.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
