# Generated by Django 5.2.5 on 2025-08-24 21:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0002_label'),
        ('processing', '0015_animal_scale_receipt_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltemplate',
            name='label_format',
            field=models.CharField(choices=[('zpl', 'ZPL (Zebra)'), ('pdf', 'PDF'), ('both', 'Both ZPL and PDF')], default='both', help_text='The format(s) this template supports.', max_length=20),
        ),
        migrations.AlterField(
            model_name='label',
            name='item_id',
            field=models.UUIDField(help_text='The ID of the associated inventory item (e.g., Carcass.id, MeatCut.id, Animal.id).'),
        ),
        migrations.AlterField(
            model_name='label',
            name='item_type',
            field=models.CharField(choices=[('carcass', 'Carcass'), ('meat_cut', 'Meat Cut'), ('offal', 'Offal'), ('by_product', 'By-Product'), ('animal', 'Animal')], help_text='Specifies what the label is for.', max_length=50),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='target_item_type',
            field=models.CharField(choices=[('carcass', 'Carcass'), ('meat_cut', 'Meat Cut'), ('offal', 'Offal'), ('by_product', 'By-Product'), ('animal', 'Animal')], help_text='Specifies which type of inventory item this template is for.', max_length=50),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='item_type',
            field=models.CharField(choices=[('carcass', 'Carcass'), ('meat_cut', 'Meat Cut'), ('offal', 'Offal'), ('by_product', 'By-Product'), ('animal', 'Animal')], help_text='The type of item being labeled.', max_length=50),
        ),
        migrations.CreateModel(
            name='AnimalLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label_type', models.CharField(choices=[('hot_carcass', 'Hot Carcass'), ('cold_carcass', 'Cold Carcass'), ('final', 'Final Product')], default='hot_carcass', help_text='Type of label for the animal.', max_length=50)),
                ('label_code', models.CharField(help_text='Unique identifier for this label.', max_length=100, unique=True)),
                ('print_date', models.DateTimeField(auto_now_add=True, help_text='When the label was printed.')),
                ('zpl_content', models.TextField(blank=True, help_text='ZPL code for this label.')),
                ('pdf_file', models.FileField(blank=True, help_text='PDF file for this label.', null=True, upload_to='animal_labels/pdf/')),
                ('animal', models.ForeignKey(help_text='The animal this label is for.', on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='processing.animal')),
                ('printed_by', models.ForeignKey(blank=True, help_text='The user who printed the label.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-print_date'],
                'unique_together': {('animal', 'label_type')},
            },
        ),
    ]
