# Generated by Django 5.2.5 on 2025-09-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0003_labeltemplate_label_format_alter_label_item_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animallabel',
            name='zpl_content',
        ),
        migrations.AddField(
            model_name='animallabel',
            name='bat_content',
            field=models.TextField(blank=True, help_text='.bat file content for easy printing.'),
        ),
        migrations.AddField(
            model_name='animallabel',
            name='prn_content',
            field=models.TextField(blank=True, help_text='TSPL/PRN code for this label.'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='label_format',
            field=models.CharField(choices=[('prn', 'PRN/TSPL'), ('pdf', 'PDF'), ('both', 'Both PRN and PDF')], default='both', help_text='The format(s) this template supports.', max_length=20),
        ),
    ]
