# Generated by Django 5.2.5 on 2026-01-23 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0004_remove_animallabel_zpl_content_and_more'),
        ('processing', '0022_alter_disassemblycut_cut_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='animallabel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='animallabel',
            name='cut',
            field=models.ForeignKey(blank=True, help_text="The disassembly cut this label is for (if label_type is 'cut').", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='processing.disassemblycut'),
        ),
        migrations.AlterField(
            model_name='animallabel',
            name='label_type',
            field=models.CharField(choices=[('hot_carcass', 'Hot Carcass'), ('cold_carcass', 'Cold Carcass'), ('final', 'Final Product'), ('cut', 'Cut')], default='hot_carcass', help_text='Type of label for the animal.', max_length=50),
        ),
    ]
