# Generated by Django 5.2.5 on 2026-03-03 18:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0005_animallabel_cut_alter_animallabel_label_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label_code', models.CharField(help_text='Unique identifier for this label.', max_length=100, unique=True)),
                ('uretici', models.CharField(help_text='Producer name', max_length=100, verbose_name='Üretici Ünvanı')),
                ('kupe_no', models.CharField(help_text='Ear tag / identification number', max_length=100, verbose_name='Küpe No')),
                ('tuccar', models.CharField(blank=True, help_text='Trader name', max_length=100, verbose_name='Tüccar Ünvanı')),
                ('kesim_tarihi', models.DateField(help_text='Slaughter date', verbose_name='Kesim Tarihi')),
                ('stt', models.DateField(help_text='Expiration date (usually slaughter date + 10 days)', verbose_name='Son Tüketim Tarihi')),
                ('siparis_no', models.CharField(blank=True, help_text='Order number', max_length=50, verbose_name='Sipariş No')),
                ('cinsi', models.CharField(choices=[('SIGIR', 'Sığır'), ('KOYUN', 'Koyun'), ('KECI', 'Keçi'), ('KUZU', 'Kuzu'), ('OGLAK', 'Oğlak'), ('BUZA', 'Buzağı'), ('DUVE', 'Düve'), ('DANA', 'Dana')], help_text='Animal type', max_length=20, verbose_name='Cinsi')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Net weight in kg', max_digits=10, verbose_name='Ağırlık (kg)')),
                ('sakatat_status', models.CharField(default='0.51', help_text='Offal status value', max_length=10, verbose_name='Sakatat Durumu')),
                ('qr_data', models.CharField(blank=True, help_text='Optional QR code data', max_length=500, verbose_name='QR Verisi')),
                ('prn_content', models.TextField(blank=True, help_text='TSPL/PRN code for this label.')),
                ('bat_content', models.TextField(blank=True, help_text='.bat file content for easy printing.')),
                ('pdf_file', models.FileField(blank=True, help_text='PDF file for this label.', null=True, upload_to='custom_labels/pdf/')),
                ('print_date', models.DateTimeField(auto_now_add=True, help_text='When the label was created.')),
                ('printed_by', models.ForeignKey(blank=True, help_text='The user who created the label.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Label',
                'verbose_name_plural': 'Custom Labels',
                'ordering': ['-print_date'],
            },
        ),
    ]
