# Generated by Django 5.2.5 on 2026-04-14 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0006_customlabel'),
        ('scales', '0010_printer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='printjob',
            name='dispatch_mode',
            field=models.CharField(choices=[('edge', 'Edge dispatch (TCP → printer)'), ('legacy_bat', 'Legacy .bat file download')], default='edge', help_text="'edge' = edge polls and dispatches. 'legacy_bat' = old .bat download flow.", max_length=16),
        ),
        migrations.AddField(
            model_name='printjob',
            name='edge_received_at',
            field=models.DateTimeField(blank=True, help_text="When edge first picked up this job (set on first 'dispatched' ack).", null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='error_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='printjob',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='printjob',
            name='printed_at',
            field=models.DateTimeField(blank=True, help_text="When edge confirmed successful print (set on 'completed' ack).", null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='prn_content',
            field=models.TextField(blank=True, help_text='TSPL bytes copied from AnimalLabel.prn_content at enqueue time. Returned inline in the edge poll response as a UTF-8 JSON string. Edge re-encodes to Windows-1254 before TCP send.'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='site',
            field=models.ForeignKey(blank=True, help_text="Which site's edge dispatches this job. Required for edge dispatch.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='scales.site'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='target_printer',
            field=models.ForeignKey(blank=True, help_text='Optional explicit printer override. If set, wins over target_role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='scales.printer'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='target_role',
            field=models.CharField(blank=True, help_text="Role-based routing: 'carcass'|'meat_cut'|'offal'|'by_product'|'animal'. Edge picks the best available Printer with this role at the job's site.", max_length=32),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='item_id',
            field=models.UUIDField(blank=True, help_text='The ID of the specific inventory item being labeled.', null=True),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='item_type',
            field=models.CharField(blank=True, choices=[('carcass', 'Carcass'), ('meat_cut', 'Meat Cut'), ('offal', 'Offal'), ('by_product', 'By-Product'), ('animal', 'Animal')], help_text='The type of item being labeled.', max_length=50),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of the print job.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['site', 'status', 'dispatch_mode'], name='labeling_pr_site_id_6bad34_idx'),
        ),
    ]
