# Generated by Django 5.2.5 on 2026-04-15 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0008_printjob_claimed_by_edge'),
        ('scales', '0012_edge_device_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printjob',
            name='claimed_by_edge',
            field=models.ForeignKey(blank=True, help_text="Edge that first ACK'd this job as dispatched (which worker took it).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_print_jobs', to='scales.edgedevice'),
        ),
    ]
