# Generated by Django 5.2.5 on 2025-08-07 23:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='A descriptive name for the service package (e.g., "Slaughter Only").', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A detailed description of what the service package includes.')),
                ('includes_disassembly', models.BooleanField(default=False, help_text='Indicates if this package includes the disassembly process.')),
                ('includes_delivery', models.BooleanField(default=False, help_text='Indicates if this package includes delivery services.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
