# Generated by Django 5.2.5 on 2025-08-07 23:09

import django.db.models.deletion
import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reception', '0002_slaughterorder_service_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('animal_type', models.CharField(choices=[('cattle', 'Cattle'), ('sheep', 'Sheep'), ('goat', 'Goat'), ('lamb', 'Lamb'), ('oglak', 'Oglak')], help_text='Type of animal (e.g., cattle, sheep, goat, lamb, oglak).', max_length=50)),
                ('identification_tag', models.CharField(help_text='Unique identification tag for the animal.', max_length=100, unique=True)),
                ('received_date', models.DateTimeField(auto_now_add=True, help_text='Date and time the animal was received.')),
                ('slaughter_date', models.DateTimeField(blank=True, help_text='Date and time the animal was slaughtered.', null=True)),
                ('status', django_fsm.FSMField(choices=[('received', 'Received'), ('slaughtered', 'Slaughtered'), ('carcass_ready', 'Carcass Ready'), ('disassembled', 'Disassembled'), ('packaged', 'Packaged'), ('delivered', 'Delivered'), ('returned', 'Returned to Owner'), ('disposed', 'Disposed')], default='received', help_text='Current status of the animal in the processing workflow.', max_length=50, protected=True)),
                ('slaughter_order', models.ForeignKey(help_text='The slaughter order this animal belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='reception.slaughterorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CattleDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('breed', models.CharField(blank=True, help_text='Breed of the cattle.', max_length=100)),
                ('horn_status', models.CharField(blank=True, help_text='Status of horns (e.g., horned, polled, dehorned).', max_length=50)),
                ('animal', models.OneToOneField(help_text='The associated cattle animal.', limit_choices_to={'animal_type': 'cattle'}, on_delete=django.db.models.deletion.CASCADE, related_name='cattle_details', to='processing.animal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoatDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('breed', models.CharField(blank=True, help_text='Breed of the goat.', max_length=100)),
                ('animal', models.OneToOneField(help_text='The associated goat animal.', limit_choices_to={'animal_type': 'goat'}, on_delete=django.db.models.deletion.CASCADE, related_name='goat_details', to='processing.animal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LambDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('animal', models.OneToOneField(help_text='The associated lamb animal.', limit_choices_to={'animal_type': 'lamb'}, on_delete=django.db.models.deletion.CASCADE, related_name='lamb_details', to='processing.animal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OglakDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('animal', models.OneToOneField(help_text='The associated oglak animal.', limit_choices_to={'animal_type': 'oglak'}, on_delete=django.db.models.deletion.CASCADE, related_name='oglak_details', to='processing.animal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SheepDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('breed', models.CharField(blank=True, help_text='Breed of the sheep.', max_length=100)),
                ('wool_type', models.CharField(blank=True, help_text='Type of wool (e.g., fine, medium, coarse).', max_length=50)),
                ('flock_id', models.CharField(blank=True, help_text='ID of the flock the sheep belongs to.', max_length=100)),
                ('animal', models.OneToOneField(help_text='The associated sheep animal.', limit_choices_to={'animal_type': 'sheep'}, on_delete=django.db.models.deletion.CASCADE, related_name='sheep_details', to='processing.animal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight recorded (e.g., live weight, hot carcass weight). For group weights, this is the average per animal.', max_digits=10)),
                ('weight_type', models.CharField(help_text="Type of weight (e.g., 'Live', 'Hot Carcass', 'Cold Carcass', 'Live Group').", max_length=100)),
                ('is_group_weight', models.BooleanField(default=False, help_text='True if this log entry represents a group weighing.')),
                ('group_quantity', models.IntegerField(blank=True, help_text='Number of animals in the group, if this is a group weight.', null=True)),
                ('group_total_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Total weight of the group, if this is a group weight.', max_digits=10, null=True)),
                ('log_date', models.DateTimeField(auto_now_add=True, help_text='Date and time the weight was logged.')),
                ('animal', models.ForeignKey(blank=True, help_text='The animal whose weight is being logged (for individual weights).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_weight_logs', to='processing.animal')),
                ('slaughter_order', models.ForeignKey(blank=True, help_text='The slaughter order this group weight belongs to (for group weights).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_weight_logs', to='reception.slaughterorder')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('animal__isnull', False), ('slaughter_order__isnull', False), _connector='OR'), name='animal_or_slaughter_order_required'), models.CheckConstraint(condition=models.Q(models.Q(('group_quantity__isnull', True), ('group_total_weight__isnull', True), ('is_group_weight', False)), models.Q(('group_quantity__isnull', False), ('group_total_weight__isnull', False), ('is_group_weight', True)), _connector='OR'), name='group_weight_consistency')],
            },
        ),
    ]
