# Generated by Django 5.2.5 on 2025-08-08 00:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattledetails',
            name='bowels_status',
            field=models.DecimalField(choices=[(0.0, 'Not Usable'), (0.5, 'Not Bad'), (1.0, 'Good')], decimal_places=1, default=0.5, help_text='Score reflecting the usability of the bowels.', max_digits=2),
        ),
        migrations.AddField(
            model_name='cattledetails',
            name='head_status',
            field=models.DecimalField(choices=[(0.0, 'Not Usable'), (0.5, 'Not Bad'), (1.0, 'Good')], decimal_places=1, default=0.5, help_text='Score reflecting the usability of the head.', max_digits=2),
        ),
        migrations.AddField(
            model_name='cattledetails',
            name='liver_status',
            field=models.DecimalField(choices=[(0.0, 'Not Usable'), (0.5, 'Not Bad'), (1.0, 'Good')], decimal_places=1, default=0.5, help_text='Score reflecting the usability of the liver.', max_digits=2),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(choices=[('cattle', 'Cattle'), ('sheep', 'Sheep'), ('goat', 'Goat'), ('lamb', 'Lamb'), ('oglak', 'Oglak'), ('calf', 'Calf'), ('heifer', 'Heifer'), ('beef', 'Beef')], help_text='Type of animal (e.g., cattle, sheep, goat, lamb, oglak, calf, heifer, beef).', max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='identification_tag',
            field=models.CharField(blank=True, help_text='Unique identification tag for the animal. System generates if not provided.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='received_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the animal was received.'),
        ),
        migrations.CreateModel(
            name='BeefDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('animal', models.OneToOneField(help_text='The associated beef animal.', limit_choices_to={'animal_type': 'beef'}, on_delete=django.db.models.deletion.CASCADE, related_name='beef_details', to='processing.animal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalfDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('animal', models.OneToOneField(help_text='The associated calf animal.', limit_choices_to={'animal_type': 'calf'}, on_delete=django.db.models.deletion.CASCADE, related_name='calf_details', to='processing.animal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeiferDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('animal', models.OneToOneField(help_text='The associated heifer animal.', limit_choices_to={'animal_type': 'heifer'}, on_delete=django.db.models.deletion.CASCADE, related_name='heifer_details', to='processing.animal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
