# Generated by Django 5.2.5 on 2025-08-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_cattledetails_bowels_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='picture',
            field=models.ImageField(blank=True, help_text='Picture of the animal.', null=True, upload_to='animal_pictures/'),
        ),
    ]
