# Generated by Django 5.2.5 on 2025-08-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_animal_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='beefdetails',
            name='leather_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The weight of the leather in kilograms.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calfdetails',
            name='leather_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The weight of the leather in kilograms.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cattledetails',
            name='leather_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The weight of the leather in kilograms.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='heiferdetails',
            name='leather_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The weight of the leather in kilograms.', max_digits=6, null=True),
        ),
    ]
