# Generated by Django 5.2.5 on 2025-08-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_goatdetails_leather_weight_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beefdetails',
            name='leather_weight_kg',
        ),
        migrations.RemoveField(
            model_name='calfdetails',
            name='leather_weight_kg',
        ),
        migrations.RemoveField(
            model_name='cattledetails',
            name='leather_weight_kg',
        ),
        migrations.RemoveField(
            model_name='goatdetails',
            name='leather_weight_kg',
        ),
        migrations.RemoveField(
            model_name='heiferdetails',
            name='leather_weight_kg',
        ),
        migrations.RemoveField(
            model_name='lambdetails',
            name='leather_weight_kg',
        ),
        migrations.RemoveField(
            model_name='oglakdetails',
            name='leather_weight_kg',
        ),
        migrations.RemoveField(
            model_name='sheepdetails',
            name='leather_weight_kg',
        ),
        migrations.AddField(
            model_name='animal',
            name='leather_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The weight of the leather in kilograms.', max_digits=6, null=True),
        ),
    ]
