# Generated by Django 5.2.5 on 2025-08-08 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_remove_beefdetails_leather_weight_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheepdetails',
            name='flock_id',
        ),
    ]
