# Generated by Django 5.2.5 on 2025-08-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0007_remove_sheepdetails_flock_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BeefDetails',
        ),
    ]
