# Generated by Django 5.2.5 on 2025-08-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0009_heiferdetails_bowels_status_heiferdetails_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calfdetails',
            name='bowels_status',
            field=models.DecimalField(choices=[(0.0, 'Not Usable'), (0.5, 'Not Bad'), (1.0, 'Good')], decimal_places=1, default=0.5, help_text='Score reflecting the usability of the bowels.', max_digits=2),
        ),
        migrations.AddField(
            model_name='calfdetails',
            name='breed',
            field=models.CharField(blank=True, help_text='Breed of the calf.', max_length=100),
        ),
        migrations.AddField(
            model_name='calfdetails',
            name='head_status',
            field=models.DecimalField(choices=[(0.0, 'Not Usable'), (0.5, 'Not Bad'), (1.0, 'Good')], decimal_places=1, default=0.5, help_text='Score reflecting the usability of the head.', max_digits=2),
        ),
        migrations.AddField(
            model_name='calfdetails',
            name='horn_status',
            field=models.CharField(blank=True, help_text='Status of horns (e.g., horned, polled, dehorned).', max_length=50),
        ),
        migrations.AddField(
            model_name='calfdetails',
            name='liver_status',
            field=models.DecimalField(choices=[(0.0, 'Not Usable'), (0.5, 'Not Bad'), (1.0, 'Good')], decimal_places=1, default=0.5, help_text='Score reflecting the usability of the liver.', max_digits=2),
        ),
    ]
