# Generated by Django 5.2.5 on 2025-08-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0010_calfdetails_bowels_status_calfdetails_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='passport_picture',
            field=models.ImageField(blank=True, help_text="Picture of the animal's passport/documentation.", null=True, upload_to='animal_passports/'),
        ),
    ]
