# Generated by Django 5.2.5 on 2025-08-13 18:41

import processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0011_animal_passport_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='passport_picture',
            field=models.ImageField(blank=True, help_text="Picture of the animal's passport/documentation.", null=True, upload_to=processing.models.animal_passport_upload_path),
        ),
        migrations.AlterField(
            model_name='animal',
            name='picture',
            field=models.ImageField(blank=True, help_text='Picture of the animal.', null=True, upload_to=processing.models.animal_picture_upload_path),
        ),
    ]
