# Generated by Django 5.2.5 on 2025-08-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0012_alter_animal_passport_picture_alter_animal_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightlog',
            name='weight_type',
            field=models.CharField(choices=[('live_weight', 'Live Weight'), ('hot_carcass_weight', 'Hot Carcass Weight'), ('cold_carcass_weight', 'Cold Carcass Weight'), ('final_weight', 'Final Weight'), ('leather_weight', 'Leather Weight'), ('live_weight Group', 'Live Weight Group'), ('hot_carcass_weight Group', 'Hot Carcass Weight Group'), ('cold_carcass_weight Group', 'Cold Carcass Weight Group'), ('final_weight Group', 'Final Weight Group')], help_text="Type of weight (e.g., 'Live', 'Hot Carcass', 'Cold Carcass', 'Live Group').", max_length=100),
        ),
    ]
