# Generated by Django 5.2.5 on 2025-08-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0013_alter_weightlog_weight_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calfdetails',
            name='head_status',
        ),
        migrations.RemoveField(
            model_name='calfdetails',
            name='horn_status',
        ),
        migrations.RemoveField(
            model_name='cattledetails',
            name='head_status',
        ),
        migrations.RemoveField(
            model_name='cattledetails',
            name='horn_status',
        ),
        migrations.RemoveField(
            model_name='heiferdetails',
            name='head_status',
        ),
        migrations.RemoveField(
            model_name='heiferdetails',
            name='horn_status',
        ),
        migrations.RemoveField(
            model_name='sheepdetails',
            name='wool_type',
        ),
        migrations.AddField(
            model_name='goatdetails',
            name='bowels_status',
            field=models.DecimalField(choices=[(0.0, 'Not Usable'), (0.5, 'Not Bad'), (1.0, 'Good')], decimal_places=1, default=0.5, help_text='Score reflecting the usability of the bowels.', max_digits=2),
        ),
        migrations.AddField(
            model_name='goatdetails',
            name='sakatat_status',
            field=models.DecimalField(choices=[(0.0, 'Not Usable'), (0.5, 'Not Bad'), (1.0, 'Good')], decimal_places=1, default=0.5, help_text='Score reflecting the usability of the sakatat (internal organs).', max_digits=2),
        ),
        migrations.AddField(
            model_name='lambdetails',
            name='bowels_status',
            field=models.DecimalField(choices=[(0.0, 'Not Usable'), (0.5, 'Not Bad'), (1.0, 'Good')], decimal_places=1, default=0.5, help_text='Score reflecting the usability of the bowels.', max_digits=2),
        ),
        migrations.AddField(
            model_name='lambdetails',
            name='sakatat_status',
            field=models.DecimalField(choices=[(0.0, 'Not Usable'), (0.5, 'Not Bad'), (1.0, 'Good')], decimal_places=1, default=0.5, help_text='Score reflecting the usability of the sakatat (internal organs).', max_digits=2),
        ),
        migrations.AddField(
            model_name='oglakdetails',
            name='bowels_status',
            field=models.DecimalField(choices=[(0.0, 'Not Usable'), (0.5, 'Not Bad'), (1.0, 'Good')], decimal_places=1, default=0.5, help_text='Score reflecting the usability of the bowels.', max_digits=2),
        ),
        migrations.AddField(
            model_name='oglakdetails',
            name='sakatat_status',
            field=models.DecimalField(choices=[(0.0, 'Not Usable'), (0.5, 'Not Bad'), (1.0, 'Good')], decimal_places=1, default=0.5, help_text='Score reflecting the usability of the sakatat (internal organs).', max_digits=2),
        ),
        migrations.AddField(
            model_name='sheepdetails',
            name='bowels_status',
            field=models.DecimalField(choices=[(0.0, 'Not Usable'), (0.5, 'Not Bad'), (1.0, 'Good')], decimal_places=1, default=0.5, help_text='Score reflecting the usability of the bowels.', max_digits=2),
        ),
        migrations.AddField(
            model_name='sheepdetails',
            name='sakatat_status',
            field=models.DecimalField(choices=[(0.0, 'Not Usable'), (0.5, 'Not Bad'), (1.0, 'Good')], decimal_places=1, default=0.5, help_text='Score reflecting the usability of the sakatat (internal organs).', max_digits=2),
        ),
    ]
