# Generated by Django 5.2.5 on 2025-08-21 19:28

import processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0014_remove_calfdetails_head_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='scale_receipt_picture',
            field=models.ImageField(blank=True, help_text="Picture of the scale receipt for the animal's weights.", null=True, upload_to=processing.models.scale_receipt_upload_path),
        ),
    ]
