# Generated by Django 5.2.5 on 2025-09-16 15:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0015_animal_scale_receipt_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeefDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('breed', models.CharField(blank=True, help_text='Breed of the beef.', max_length=100)),
                ('liver_status', models.DecimalField(choices=[(0.0, 'Not Usable'), (0.5, 'Not Bad'), (1.0, 'Good')], decimal_places=1, default=0.5, help_text='Score reflecting the usability of the liver.', max_digits=2)),
                ('bowels_status', models.DecimalField(choices=[(0.0, 'Not Usable'), (0.5, 'Not Bad'), (1.0, 'Good')], decimal_places=1, default=0.5, help_text='Score reflecting the usability of the bowels.', max_digits=2)),
                ('animal', models.OneToOneField(help_text='The associated beef animal.', limit_choices_to={'animal_type': 'beef'}, on_delete=django.db.models.deletion.CASCADE, related_name='beef_details', to='processing.animal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
