# Generated by Django 5.2.5 on 2025-09-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0016_beefdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beefdetails',
            name='liver_status',
        ),
        migrations.RemoveField(
            model_name='calfdetails',
            name='liver_status',
        ),
        migrations.RemoveField(
            model_name='cattledetails',
            name='liver_status',
        ),
        migrations.RemoveField(
            model_name='heiferdetails',
            name='liver_status',
        ),
        migrations.AddField(
            model_name='beefdetails',
            name='sakatat_status',
            field=models.DecimalField(choices=[(0.0, 'Not Usable'), (0.5, 'Not Bad'), (1.0, 'Good')], decimal_places=1, default=0.5, help_text='Score reflecting the usability of the sakatat (internal organs).', max_digits=2),
        ),
        migrations.AddField(
            model_name='calfdetails',
            name='sakatat_status',
            field=models.DecimalField(choices=[(0.0, 'Not Usable'), (0.5, 'Not Bad'), (1.0, 'Good')], decimal_places=1, default=0.5, help_text='Score reflecting the usability of the sakatat (internal organs).', max_digits=2),
        ),
        migrations.AddField(
            model_name='cattledetails',
            name='sakatat_status',
            field=models.DecimalField(choices=[(0.0, 'Not Usable'), (0.5, 'Not Bad'), (1.0, 'Good')], decimal_places=1, default=0.5, help_text='Score reflecting the usability of the sakatat (internal organs).', max_digits=2),
        ),
        migrations.AddField(
            model_name='heiferdetails',
            name='sakatat_status',
            field=models.DecimalField(choices=[(0.0, 'Not Usable'), (0.5, 'Not Bad'), (1.0, 'Good')], decimal_places=1, default=0.5, help_text='Score reflecting the usability of the sakatat (internal organs).', max_digits=2),
        ),
    ]
