# Generated by Django 5.2.5 on 2025-11-21 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0017_remove_beefdetails_liver_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Name of the part (e.g., Ribeye, Liver, Leg).', max_length=100)),
                ('animal_type', models.CharField(choices=[('cattle', 'Cattle'), ('sheep', 'Sheep'), ('goat', 'Goat'), ('lamb', 'Lamb'), ('oglak', 'Oglak'), ('calf', 'Calf'), ('heifer', 'Heifer'), ('beef', 'Beef')], help_text='The animal type this part belongs to.', max_length=50)),
                ('code', models.CharField(help_text='Unique code for this part type (used for barcodes/labels).', max_length=50, unique=True)),
            ],
            options={
                'ordering': ['animal_type', 'name'],
                'unique_together': {('name', 'animal_type')},
            },
        ),
        migrations.CreateModel(
            name='DisassembledPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of the part in kg.', max_digits=8)),
                ('qr_code', models.ImageField(blank=True, help_text='QR code image for this specific part.', null=True, upload_to='part_qr_codes/')),
                ('label_id', models.CharField(blank=True, help_text='Unique label ID for this part.', max_length=100, unique=True)),
                ('animal', models.ForeignKey(help_text='The animal this part came from.', on_delete=django.db.models.deletion.CASCADE, related_name='disassembled_parts', to='processing.animal')),
                ('part_type', models.ForeignKey(help_text='The type of part.', on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='processing.parttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
