# Generated by Django 5.2.5 on 2025-11-21 16:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0018_parttype_disassembledpart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parttype',
            unique_together=None,
        ),
        migrations.CreateModel(
            name='DisassemblyCut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cut_name', models.CharField(help_text='Name of the cut (depends on animal type)', max_length=100)),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Weight of this cut in kg', max_digits=7)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disassembly_cuts', to='processing.animal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DisassembledPart',
        ),
        migrations.DeleteModel(
            name='PartType',
        ),
    ]
