# Generated by Django 5.2.5 on 2025-11-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0020_alter_disassemblycut_cut_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disassemblycut',
            name='cut_name',
            field=models.CharField(choices=[('neck', 'Neck'), ('front_leg', 'Front Leg'), ('rib', 'Rib'), ('breast', 'Breast / Plate'), ('flank', 'Flank'), ('tenderloin', 'Tenderloin'), ('ribeye', 'Ribeye'), ('topside', 'Topside / Tranç'), ('knuckle', 'Knuckle / Yumurta'), ('round', 'Round / Nuar'), ('ground_beef', 'Ground Beef'), ('trim', 'Trim'), ('stew_cubes', 'Stew Cubes'), ('boneless_meat', 'Boneless Meat (Total)'), ('shoulder', 'Shoulder'), ('neck', 'Neck'), ('rib_cage', 'Rib Cage'), ('chop', 'Chop / Rack'), ('breast', 'Breast'), ('fillet', 'Fillet'), ('back_strip', 'Back Strip'), ('leg', 'Leg'), ('shank', 'Shank'), ('kulbasti', 'Kulbasti'), ('hastamalik', 'Soup Bones'), ('trim', 'Trim')], help_text='Name of the cut (depends on animal type)', max_length=100),
        ),
    ]
