# Generated by Django 5.2.5 on 2026-02-17 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0022_alter_disassemblycut_cut_name'),
        ('scales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disassemblycut',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_cuts', to='scales.disassemblysession'),
        ),
    ]
