# Generated by Django 5.2.5 on 2026-05-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0025_disassemblycut_cut_name_free_text'),
        ('reception', '0007_slaughterorder_destination_client'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['status', 'received_date'], name='processing__status_f08c66_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['identification_tag'], name='processing__identif_3f9512_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['slaughter_order', 'status'], name='processing__slaught_038267_idx'),
        ),
        migrations.AddIndex(
            model_name='weightlog',
            index=models.Index(fields=['log_date'], name='processing__log_dat_03a878_idx'),
        ),
        migrations.AddIndex(
            model_name='weightlog',
            index=models.Index(fields=['weight_type', 'log_date'], name='processing__weight__23c907_idx'),
        ),
        migrations.AddIndex(
            model_name='weightlog',
            index=models.Index(fields=['animal', 'weight_type'], name='processing__animal__6a111e_idx'),
        ),
    ]
