# Generated by Django 5.2.5 on 2026-03-25 16:12

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(help_text='Business / display name', max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_full_name', models.CharField(blank=True, max_length=255)),
                ('company_address', models.CharField(blank=True, max_length=500)),
                ('license_no', models.CharField(blank=True, max_length=64)),
                ('operation_no', models.CharField(blank=True, max_length=64)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('printer_turkish_mode', models.CharField(default='unicode', max_length=32)),
                ('timezone', models.CharField(default='Europe/Istanbul', max_length=64)),
                ('language_code', models.CharField(default='tr', max_length=16)),
            ],
            options={
                'db_table': 'tenants_client',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.client')),
            ],
            options={
                'db_table': 'tenants_domain',
            },
        ),
    ]
