# Generated by Django 5.2.5 on 2026-03-28 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_registration_request'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailtenantmembership',
            new_name='tenants_ema_email_n_0a8f45_idx',
            old_name='tenants_ema_email_n_7a8b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantregistrationrequest',
            new_name='tenants_ten_status_13c830_idx',
            old_name='tenants_ten_status_d73870_idx',
        ),
    ]
