# Generated by Django 5.2.5 on 2026-04-02 00:56

import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_client_verbose_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional branding image in the app header.', null=True, upload_to=tenants.models.tenant_logo_upload_to, verbose_name='Logo'),
        ),
    ]
