# Generated by Django 5.2.5 on 2026-04-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_client_logo_upload_to_callable'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtenantmembership',
            name='phone_normalized',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='emailtenantmembership',
            name='role',
            field=models.CharField(blank=True, default='', help_text='Mirrors users.User.role from the tenant schema (synced on save).', max_length=50),
        ),
    ]
