# Generated by Django 5.2.5 on 2026-04-03 14:36

import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_emailtenantmembership_phone_normalized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional branding image in the app header.', null=True, storage=tenants.models._get_public_storage, upload_to=tenants.models.tenant_logo_upload_to, verbose_name='Logo'),
        ),
    ]
