# Generated by Django 5.2.5 on 2026-04-14 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_client_registered_province_plaka'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeSetupCodeIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('tenant_schema', models.CharField(help_text='Cached schema_name for fast lookup without JOIN.', max_length=63)),
                ('setup_code_id', models.UUIDField(help_text='PK of the EdgeSetupCode row in the tenant schema.')),
                ('expires_at', models.DateTimeField()),
                ('is_consumed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_code_index_entries', to='tenants.client')),
            ],
            options={
                'db_table': 'tenants_edge_setup_code_index',
                'indexes': [models.Index(fields=['code'], name='tenants_edg_code_78ef7e_idx'), models.Index(fields=['tenant', '-created_at'], name='tenants_edg_tenant__b0bd1a_idx')],
            },
        ),
    ]
