# Generated by Django 5.2.5 on 2026-04-15 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_add_edge_device_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='edgedeviceindex',
            new_name='tenants_edg_tenant__d864ad_idx',
            old_name='tenants_edg_dev_tenant_idx',
        ),
    ]
