# Generated by Django 5.2.5 on 2025-08-07 23:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='A descriptive name for the report (e.g., "Daily Throughput Report").', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Explains the purpose and content of the report.')),
                ('report_type', models.CharField(choices=[('operational', 'Operational'), ('financial', 'Financial'), ('analytics', 'Analytics')], help_text='Categorizes the report.', max_length=50)),
                ('configuration', models.JSONField(blank=True, help_text='Stores parameters and settings specific to how this report is generated.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the report was generated.')),
                ('start_date', models.DateField(blank=True, help_text='The start date of the data period covered by the report.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='The end date of the data period covered by the report.', null=True)),
                ('file_path', models.CharField(blank=True, help_text='Path to the generated report file (e.g., PDF, CSV).', max_length=255, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', help_text='Status of the report generation.', max_length=20)),
                ('generated_by', models.ForeignKey(blank=True, help_text='The user who generated the report.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report_definition', models.ForeignKey(help_text='The definition of the report that was generated.', on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='reporting.report')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
