# Generated by Django 5.2.5 on 2025-10-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='default_filters',
            field=models.JSONField(blank=True, help_text='Default filters for the report (animal types, clients, etc.).', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom Date Range')], default='daily', help_text='How often this report is generated.', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='output_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('both', 'Both PDF and Excel')], default='both', help_text='Output format for the report.', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='requires_date_range',
            field=models.BooleanField(default=True, help_text='Whether this report requires a date range to be specified.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the report is currently available for generation.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(help_text='A descriptive name for the report (e.g., "Daily Slaughter Report").', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('daily_slaughter', 'Daily Slaughter'), ('daily_throughput', 'Daily Throughput'), ('daily_weights', 'Daily Weight Analysis'), ('daily_clients', 'Daily Client Activity'), ('monthly_operations', 'Monthly Operations'), ('monthly_yield', 'Monthly Yield Analysis'), ('monthly_financial', 'Monthly Financial'), ('monthly_clients', 'Monthly Client Performance'), ('yearly_operations', 'Annual Operations'), ('yearly_yield', 'Annual Yield Trends'), ('yearly_financial', 'Annual Financial'), ('yearly_clients', 'Annual Client Analysis')], help_text='Categorizes the report.', max_length=50),
        ),
    ]
