# Generated by Django 5.2.5 on 2026-02-17 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processing', '0022_alter_disassemblycut_cut_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScaleDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device_id', models.CharField(max_length=50)),
                ('global_device_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('device_type', models.CharField(default='disassembly', max_length=50)),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='scales.edgedevice')),
            ],
        ),
        migrations.CreateModel(
            name='DisassemblySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('operator', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('auto_closed', 'Auto-closed')], default='pending', max_length=50)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('total_weight_grams', models.IntegerField(default=0)),
                ('event_count', models.IntegerField(default=0)),
                ('close_reason', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scale_sessions', to='processing.animal')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='scales.scaledevice')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scale_sessions', to='scales.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PLUItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plu_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('name_turkish', models.CharField(blank=True, max_length=16)),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('price_cents', models.IntegerField(default=0)),
                ('unit_type', models.CharField(default='kg', max_length=10)),
                ('tare_grams', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Dana', 'Dana'), ('Kuzu', 'Kuzu'), ('Koyun', 'Koyun'), ('Oglak', 'Oglak'), ('Genel', 'Genel')], default='Genel', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plu_items', to='scales.site')),
            ],
        ),
        migrations.CreateModel(
            name='OrphanedBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('event_count', models.IntegerField(default=0)),
                ('total_weight_grams', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reconciled', 'Reconciled'), ('ignored', 'Ignored')], default='pending', max_length=50)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled_by', models.CharField(blank=True, max_length=100)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orphaned_batches', to='scales.edgedevice')),
                ('reconciled_to_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_batches', to='scales.disassemblysession')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orphaned_batches', to='scales.scaledevice')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orphaned_batches', to='scales.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='edgedevice',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='scales.site'),
        ),
        migrations.CreateModel(
            name='WeighingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plu_code', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('weight_grams', models.IntegerField()),
                ('barcode', models.CharField(max_length=50)),
                ('scale_timestamp', models.DateTimeField()),
                ('edge_received_at', models.DateTimeField()),
                ('cloud_received_at', models.DateTimeField(auto_now_add=True)),
                ('edge_event_id', models.CharField(max_length=100, unique=True)),
                ('offline_batch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighing_events', to='processing.animal')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='scales.scaledevice')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='scales.disassemblysession')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weighing_events', to='scales.site')),
            ],
        ),
        migrations.AddConstraint(
            model_name='scaledevice',
            constraint=models.UniqueConstraint(fields=('edge', 'device_id'), name='scales_scaledevice_edge_device_id'),
        ),
        migrations.AddConstraint(
            model_name='pluitem',
            constraint=models.UniqueConstraint(fields=('site', 'plu_code'), name='scales_pluitem_site_plu'),
        ),
        migrations.AddIndex(
            model_name='weighingevent',
            index=models.Index(fields=['site', 'scale_timestamp'], name='scales_weig_site_id_5eb070_idx'),
        ),
        migrations.AddIndex(
            model_name='weighingevent',
            index=models.Index(fields=['session'], name='scales_weig_session_5fa0d5_idx'),
        ),
        migrations.AddIndex(
            model_name='weighingevent',
            index=models.Index(fields=['animal'], name='scales_weig_animal__6336c3_idx'),
        ),
        migrations.AddIndex(
            model_name='weighingevent',
            index=models.Index(fields=['offline_batch_id'], name='scales_weig_offline_a548b8_idx'),
        ),
        migrations.AddIndex(
            model_name='weighingevent',
            index=models.Index(fields=['edge_event_id'], name='scales_weig_edge_ev_8a24f9_idx'),
        ),
    ]
