# Generated by Django 5.2.5 on 2026-02-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0004_add_offline_batch_ack'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingevent',
            name='product_display_override',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
