# Generated by Django 5.2.5 on 2026-02-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0005_add_product_display_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingevent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weighingevent',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
