# Generated by Django 5.2.5 on 2026-02-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0008_backfill_session_animals'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='weighingevent',
            new_name='scales_weig_assigne_164d71_idx',
            old_name='scales_weig_assigne_idx',
        ),
    ]
