# Generated by Django 5.2.5 on 2026-04-14 03:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0009_rename_scales_weig_assigne_idx_scales_weig_assigne_164d71_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('local_printer_id', models.CharField(help_text="Stable local ID set by the operator (e.g. 'carcass-01'). Unique within one edge.", max_length=64)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('carcass', 'Carcass'), ('meat_cut', 'Meat Cut'), ('offal', 'Offal'), ('by_product', 'By-Product'), ('animal', 'Animal'), ('generic', 'Generic')], default='generic', help_text='Routing role. PrintJobs with target_role=X go to any online Printer with role=X at the same site.', max_length=32)),
                ('transport', models.CharField(default='tcp', max_length=16)),
                ('host', models.CharField(help_text='IPv4 address on the site LAN.', max_length=64)),
                ('port', models.PositiveIntegerField(default=9100)),
                ('model', models.CharField(blank=True, help_text="e.g. 'TE210'", max_length=64)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='unknown', max_length=16)),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Lower = preferred. Use 100/200 for primary/backup. Edge resolves by this value.')),
                ('enabled', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(blank=True, help_text='Firmware version from ~!T query.', max_length=64)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='scales.edgedevice')),
                ('site', models.ForeignKey(help_text='Denormalized from edge.site for efficient site-wide queries.', on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='scales.site')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'role', 'status'], name='scales_prin_site_id_2367fd_idx'), models.Index(fields=['edge', '-last_seen_at'], name='scales_prin_edge_id_e4871a_idx')],
                'constraints': [models.UniqueConstraint(fields=('edge', 'local_printer_id'), name='scales_printer_edge_local_id')],
            },
        ),
    ]
