# Generated by Django 5.2.5 on 2026-04-14 20:47

import django.db.models.deletion
import scales.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0010_printer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeSetupCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(default=scales.models.generate_setup_code, max_length=16, unique=True)),
                ('edge_name', models.CharField(blank=True, help_text='Pre-configured name for the Edge device.', max_length=200)),
                ('printers_config', models.JSONField(blank=True, default=list, help_text='Pre-configured printer list for the Edge. Each entry: {"localPrinterId": "carcass-01", "host": "192.168.1.220", "port": 9100, "role": "carcass", "displayName": "Carcass Line"}. Returned in the /activate response so the Edge auto-configures printers.')),
                ('expires_at', models.DateTimeField(help_text='Code expires after this time (default 48 hours from creation).')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_codes', to='scales.site')),
                ('used_by_edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_code', to='scales.edgedevice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', '-created_at'], name='scales_edge_site_id_6aa93a_idx')],
            },
        ),
    ]
