# Generated by Django 5.2.5 on 2026-04-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0011_add_edge_setup_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgedevice',
            name='health',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
