# Generated by Django 5.2.5 on 2026-04-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0012_edge_device_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='warnings',
            field=models.CharField(blank=True, help_text="Comma-separated TSPL warnings from edge (e.g. 'paper_low,ribbon_low'). Decoded from <ESC>!S response.", max_length=255),
        ),
        migrations.AlterField(
            model_name='printer',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('online', 'Online'), ('warning', 'Warning'), ('offline', 'Offline'), ('error', 'Error')], default='unknown', max_length=16),
        ),
    ]
