# Generated by Django 5.2.5 on 2025-08-07 23:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ByProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('byproduct_type', models.CharField(help_text="Describes the type of by-product (e.g., 'Skin', 'Head').", max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='The weight of the by-product.', max_digits=10, null=True)),
                ('disposition', models.CharField(choices=[('returned_to_owner', 'Returned to Owner'), ('for_sale', 'For Sale'), ('disposed', 'Disposed')], help_text='How the by-product will be handled.', max_length=50)),
                ('label_id', models.CharField(blank=True, help_text='Reference to a physical label printed for this by-product.', max_length=100, null=True, unique=True)),
                ('animal', models.ForeignKey(help_text='The animal this by-product came from.', on_delete=django.db.models.deletion.CASCADE, related_name='by_products', to='processing.animal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carcass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('weight', models.DecimalField(decimal_places=2, help_text='The weight of the carcass (e.g., hot or cold carcass weight).', max_digits=10)),
                ('status', models.CharField(choices=[('chilling', 'Chilling'), ('disassembly_ready', 'Disassembly Ready'), ('frozen', 'Frozen'), ('dispatched', 'Dispatched')], default='chilling', help_text='Current status of the carcass.', max_length=50)),
                ('disposition', models.CharField(choices=[('returned_to_owner', 'Returned to Owner'), ('for_sale', 'For Sale'), ('disposed', 'Disposed')], help_text='How the carcass will be handled.', max_length=50)),
                ('animal', models.OneToOneField(help_text='The animal this carcass belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='carcass', to='processing.animal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label_code', models.CharField(help_text='A unique code printed on the label (e.g., QR code, barcode).', max_length=100, unique=True)),
                ('item_type', models.CharField(choices=[('carcass', 'Carcass'), ('meat_cut', 'Meat Cut'), ('offal', 'Offal'), ('by_product', 'By-Product')], help_text='Specifies what the label is for.', max_length=50)),
                ('item_id', models.UUIDField(help_text='The ID of the associated inventory item (e.g., Carcass.id, MeatCut.id).')),
                ('print_date', models.DateTimeField(auto_now_add=True, help_text='When the label was printed.')),
                ('printed_by', models.ForeignKey(blank=True, help_text='The user who printed the label.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeatCut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cut_type', models.CharField(help_text="Describes the specific cut (e.g., 'Front Quarter', 'Hind Quarter').", max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, help_text='The weight of this specific cut.', max_digits=10)),
                ('disposition', models.CharField(choices=[('returned_to_owner', 'Returned to Owner'), ('for_sale', 'For Sale'), ('disposed', 'Disposed')], help_text='How the cut will be handled.', max_length=50)),
                ('label_id', models.CharField(blank=True, help_text='Reference to a physical label printed for this cut.', max_length=100, null=True, unique=True)),
                ('carcass', models.ForeignKey(help_text='The carcass from which this cut was derived.', on_delete=django.db.models.deletion.CASCADE, related_name='meat_cuts', to='inventory.carcass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('offal_type', models.CharField(help_text="Describes the type of offal (e.g., 'Liver', 'Kidneys').", max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, help_text='The weight of the offal.', max_digits=10)),
                ('disposition', models.CharField(choices=[('returned_to_owner', 'Returned to Owner'), ('for_sale', 'For Sale'), ('disposed', 'Disposed')], help_text='How the offal will be handled.', max_length=50)),
                ('label_id', models.CharField(blank=True, help_text='Reference to a physical label printed for this offal.', max_length=100, null=True, unique=True)),
                ('animal', models.ForeignKey(help_text='The animal this offal came from.', on_delete=django.db.models.deletion.CASCADE, related_name='offals', to='processing.animal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
