# Generated by Django 5.2.5 on 2025-08-09 00:08

import django.db.models.deletion
import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text="A unique name for the storage location (e.g., 'Freezer 1', 'Cooler A, Shelf 3').", max_length=100, unique=True)),
                ('location_type', models.CharField(choices=[('freezer', 'Freezer'), ('cooler', 'Cooler'), ('dry_storage', 'Dry Storage')], help_text='Categorizes the type of storage.', max_length=50)),
                ('capacity_kg', models.DecimalField(blank=True, decimal_places=2, help_text='The storage capacity in kilograms.', max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='carcass',
            name='weight',
        ),
        migrations.AddField(
            model_name='carcass',
            name='cold_carcass_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The weight of the carcass after chilling.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='carcass',
            name='hot_carcass_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The weight of the carcass immediately after slaughter.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='carcass',
            name='status',
            field=django_fsm.FSMField(choices=[('chilling', 'Chilling'), ('disassembly_ready', 'Disassembly Ready'), ('frozen', 'Frozen'), ('dispatched', 'Dispatched')], default='chilling', help_text='Current status of the carcass.', max_length=50, protected=True),
        ),
        migrations.AddField(
            model_name='byproduct',
            name='storage_location',
            field=models.ForeignKey(blank=True, help_text='The current physical storage location of the by-product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='by_products', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='carcass',
            name='storage_location',
            field=models.ForeignKey(blank=True, help_text='The current physical storage location of the carcass.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carcasses', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='meatcut',
            name='storage_location',
            field=models.ForeignKey(blank=True, help_text='The current physical storage location of the meat cut.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meat_cuts', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='offal',
            name='storage_location',
            field=models.ForeignKey(blank=True, help_text='The current physical storage location of the offal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offals', to='inventory.storagelocation'),
        ),
    ]
