# Generated by Django 5.2.5 on 2025-08-09 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_storagelocation_remove_carcass_weight_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
    ]
