# Generated by Django 5.2.5 on 2025-08-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_delete_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='byproduct',
            name='byproduct_type',
            field=models.CharField(choices=[('SKIN', 'Skin'), ('HEAD', 'Head'), ('FEET', 'Feet')], help_text="Describes the type of by-product (e.g., 'Skin', 'Head').", max_length=100),
        ),
        migrations.AlterField(
            model_name='meatcut',
            name='cut_type',
            field=models.CharField(choices=[('WHOLE_BONELESS', 'Whole Piece Boneless'), ('NECK', 'Neck'), ('CHUCK', 'Chuck'), ('RIBEYE', 'Ribeye'), ('SHANK', 'Shank'), ('KNUCKLE', 'Knuckle'), ('STRIPLOIN', 'Striploin'), ('TENDERLOIN', 'Tenderloin'), ('FLANK', 'Flank'), ('FILLET', 'Fillet'), ('BRISKET', 'Brisket'), ('GROUND_BEEF', 'Ground Beef'), ('STEW_MEAT', 'Stew Meat'), ('MEATBALL_MIX', 'Meatball Mix'), ('SAUSAGE', 'Sausage'), ('BRAISED_MEAT', 'Braised Meat'), ('WHOLE_BONELESS', 'Whole Piece Boneless'), ('NECK', 'Neck'), ('SHOULDER', 'Shoulder'), ('LEG', 'Leg'), ('RACK', 'Rack'), ('FLANK', 'Flank'), ('CHOP', 'Chop'), ('GRILLED_CUTLET', 'Grilled Cutlet'), ('EMPTY', 'Empty')], help_text="Describes the specific cut (e.g., 'Front Quarter', 'Hind Quarter').", max_length=100),
        ),
        migrations.AlterField(
            model_name='offal',
            name='offal_type',
            field=models.CharField(choices=[('LIVER', 'Beef Liver'), ('HEART', 'Heart'), ('SPLEEN', 'Spleen'), ('HEAD_MEAT', 'Head Meat'), ('CAUL_FAT', 'Caul Fat'), ('KIDNEY_FAT', 'Kidney Fat'), ('OMENTUM_FAT', 'Omentum Fat'), ('LIVER_SET', 'Lamb Liver Set'), ('HEAD', 'Head')], help_text="Describes the type of offal (e.g., 'Liver', 'Kidneys').", max_length=100),
        ),
    ]
