# Generated by Django 5.2.5 on 2025-08-07 01:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_clientprofile_contact_person_clientprofile_tax_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaughterOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BILLED', 'Billed')], default='PENDING', max_length=20)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slaughter_orders', to='users.clientprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
