# Generated by Django 5.2.5 on 2025-08-07 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterorder',
            name='service_package',
            field=models.ForeignKey(blank=True, help_text='The service package selected for this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slaughter_orders', to='core.servicepackage'),
        ),
    ]
