# Generated by Django 5.2.5 on 2025-08-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_slaughterorder_service_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterorder',
            name='destination',
            field=models.CharField(blank=True, help_text='Specifies the final destination or market for the animals/products in this order.', max_length=255, null=True),
        ),
    ]
