# Generated by Django 5.2.5 on 2025-08-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_slaughterorder_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterorder',
            name='slaughter_order_no',
            field=models.CharField(blank=True, help_text='A human-readable, unique order number. Automatically generated if not provided.', max_length=50, null=True, unique=True),
        ),
    ]
