# Generated by Django 5.2.5 on 2025-08-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_slaughterorder_slaughter_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaughterorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BILLED', 'Billed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
