# Generated by Django 5.2.5 on 2025-08-13 00:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_alter_slaughterorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slaughterorder',
            name='order_date',
        ),
        migrations.AddField(
            model_name='slaughterorder',
            name='order_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
