# Generated by Django 5.2.5 on 2026-05-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servicepackage_name_tr_description_tr'),
        ('reception', '0007_slaughterorder_destination_client'),
        ('users', '0009_clientprofile_default_destination_client'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='slaughterorder',
            index=models.Index(fields=['order_datetime'], name='reception_s_order_d_a8f671_idx'),
        ),
        migrations.AddIndex(
            model_name='slaughterorder',
            index=models.Index(fields=['status', 'order_datetime'], name='reception_s_status_ffdb0e_idx'),
        ),
    ]
