"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

import logging
import os
from pathlib import Path

from decouple import Csv, config
from django.core.exceptions import ImproperlyConfigured
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _cookie_samesite(value: str | None) -> str | None:
    """
    Parse SESSION_COOKIE_SAMESITE / CSRF_COOKIE_SAMESITE from env.

    Use `none` (or `null`) for cross-origin credentialed fetch (SPA on :3000 → tenant API on :8000).
    This must become the string ``\"none\"`` so Django emits ``SameSite=None`` on Set-Cookie.
    Returning Python ``None`` means *omit* the attribute (browser default ≈ Lax), which breaks
    that flow. Production: pair with SESSION_COOKIE_SECURE=True (required by browsers except
    localhost/127.0.0.1 HTTP in Chromium).
    """
    if value is None or not str(value).strip():
        return "Lax"
    v = str(value).strip().lower()
    if v in ("none", "null"):
        return "none"
    if v == "lax":
        return "Lax"
    if v == "strict":
        return "Strict"
    return "Lax"


# Multi-tenant mode uses PostgreSQL + django-tenants. SQLite is only for legacy / Docker collectstatic.
USE_SQLITE = config("USE_SQLITE", default=False, cast=bool)
USE_MULTITENANT = not USE_SQLITE

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv())


def _resolve_tenant_base_domain() -> str:
    """
    Host suffix for tenant hostnames: {schema}.{TENANT_BASE_DOMAIN}.

    - If TENANT_BASE_DOMAIN is set in the environment, use it.
    - If unset and DEBUG is True, default to localhost (local dev without extra env).
    - If unset and not DEBUG, derive from the first ALLOWED_HOSTS entry that looks like
      a subdomain wildcard (e.g. ".carnitrack.example.com" -> "carnitrack.example.com").
    - Otherwise raise ImproperlyConfigured so production never silently uses a wrong domain.
    """
    explicit = config("TENANT_BASE_DOMAIN", default="").strip()
    if explicit:
        return explicit
    if DEBUG:
        return "localhost"
    for host in ALLOWED_HOSTS:
        h = str(host).strip()
        if h.startswith(".") and h.count(".") >= 2:
            return h.lstrip(".")
    raise ImproperlyConfigured(
        "TENANT_BASE_DOMAIN is not set. Set TENANT_BASE_DOMAIN in the environment "
        "(e.g. carnitrack.yourdomain.com), or add a wildcard host to ALLOWED_HOSTS "
        "(e.g. .carnitrack.yourdomain.com) so tenant hostnames "
        "{schema}.<suffix> can be derived. When DEBUG is True, localhost is used if unset."
    )


TENANT_BASE_DOMAIN = _resolve_tenant_base_domain()
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", cast=Csv())
SESSION_COOKIE_DOMAIN = config("SESSION_COOKIE_DOMAIN", default=None)
CSRF_COOKIE_DOMAIN = config("CSRF_COOKIE_DOMAIN", default=SESSION_COOKIE_DOMAIN or None)
SESSION_COOKIE_SAMESITE = _cookie_samesite(config("SESSION_COOKIE_SAMESITE", default="Lax"))
CSRF_COOKIE_SAMESITE = _cookie_samesite(config("CSRF_COOKIE_SAMESITE", default="Lax"))
CSRF_COOKIE_HTTPONLY = config("CSRF_COOKIE_HTTPONLY", default=False, cast=bool)
CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", default="", cast=Csv())
CORS_ALLOW_CREDENTIALS = config("CORS_ALLOW_CREDENTIALS", default=True, cast=bool)

# django-cors-headers: regexes for dev SPAs on *.localhost (pomet.localhost:3000, etc.)
# so each new tenant subdomain does not require editing CORS_ALLOWED_ORIGINS.
CORS_ALLOWED_ORIGIN_REGEXES: list[str] = []
if DEBUG and USE_MULTITENANT and config("CORS_DEV_LOCALHOST_REGEX", default=True, cast=bool):
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^https?://([\w.-]+\.)?localhost(:\d+)?$",
        r"^https?://127\.0\.0\.1(:\d+)?$",
    ]

# Django CSRF: wildcard subdomains use http(s)://*.host:port (see CsrfViewMiddleware).
if DEBUG and USE_MULTITENANT and config("CSRF_DEV_TRUST_LOCALHOST", default=True, cast=bool):
    _csrf_dev_extra = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:5173",
        "http://*.localhost:3000",
        "http://*.localhost:5173",
        "https://localhost:3000",
        "https://*.localhost:3000",
        "https://*.localhost:5173",
    ]
    _csrf_seen: set[str] = set()
    _csrf_merged: list[str] = []
    for _o in list(CSRF_TRUSTED_ORIGINS) + _csrf_dev_extra:
        if _o not in _csrf_seen:
            _csrf_seen.add(_o)
            _csrf_merged.append(_o)
    CSRF_TRUSTED_ORIGINS = _csrf_merged

# Application definition
SHARED_APPS = [
    "django_tenants",
    "django.contrib.contenttypes",
    "django.contrib.admin",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "tenants",
    "tailwind",
    "widget_tweaks",
    "theme",
    "storages",
]

TENANT_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django_fsm",
    "users",
    "reception",
    "processing",
    "inventory",
    "portal",
    "core",
    "labeling",
    "reporting",
    "scales",
]

_LEGACY_INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "django_fsm",
    "tailwind",
    "widget_tweaks",
    "users",
    "reception",
    "processing",
    "inventory",
    "portal",
    "core",
    "labeling",
    "reporting",
    "scales",
    "theme",
    "storages",
]

if USE_MULTITENANT:
    INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]
else:
    INSTALLED_APPS = _LEGACY_INSTALLED_APPS

_MULTITENANT_MIDDLEWARE = [
    "django_tenants.middleware.main.TenantMainMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "tenants.middleware.ClearLegacyMessagesCookieMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

_LEGACY_MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "tenants.middleware.ClearLegacyMessagesCookieMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

MIDDLEWARE = _MULTITENANT_MIDDLEWARE if USE_MULTITENANT else _LEGACY_MIDDLEWARE

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
            ],
        },
    },
]

if USE_MULTITENANT:
    TEMPLATES[0]["OPTIONS"]["context_processors"].append("tenants.context_processors.tenant_context")

WSGI_APPLICATION = "config.wsgi.application"

# -------------------------
# Database Configuration
# -------------------------
# Pick exactly one: Cloud SQL, local PostgreSQL (dev), or SQLite (legacy / Docker image build only).
DATABASES = {}

# Cloud SQL (Production: Unix socket, Local via Proxy: TCP)
if config("USE_CLOUD_SQL", default=False, cast=bool):
    # Check if we should use TCP mode (for local Cloud SQL Proxy)
    if config("DB_HOST", default=""):
        # TCP mode: DB_HOST is set (e.g., 127.0.0.1 for local proxy)
        DATABASES["default"] = {
            "ENGINE": "django_tenants.postgresql_backend",
            "NAME": config("DB_NAME"),
            "USER": config("DB_USER"),
            "PASSWORD": config("DB_PASSWORD"),
            "HOST": config("DB_HOST"),
            "PORT": config("DB_PORT", default="5432"),
        }
    else:
        # Unix socket mode: Cloud Run with mounted /cloudsql directory
        DATABASES["default"] = {
            "ENGINE": "django_tenants.postgresql_backend",
            "NAME": config("DB_NAME"),
            "USER": config("DB_USER"),
            "PASSWORD": config("DB_PASSWORD"),
            "HOST": f"/cloudsql/{config('CLOUD_SQL_CONNECTION_NAME')}",
            "PORT": "",
        }

# Local Postgres (development: Homebrew / Docker Postgres on your machine)
elif config("USE_LOCAL_POSTGRES", default=False, cast=bool):
    DATABASES["default"] = {
        "ENGINE": "django_tenants.postgresql_backend",
        "NAME": config("DB_NAME", default="carnitrack_dev"),
        "USER": config("DB_USER", default="postgres"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
    }

elif config("USE_SQLITE", default=False, cast=bool):
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }

else:
    raise ImproperlyConfigured(
        "Database not configured. Set USE_CLOUD_SQL=True (Cloud Run / proxy), "
        "USE_LOCAL_POSTGRES=True (local PostgreSQL, see env/examples/.env.dev.example), or "
        "USE_SQLITE=True (legacy only; used in the Docker image build)."
    )

if USE_MULTITENANT:
    DATABASE_ROUTERS = ["django_tenants.routers.TenantSyncRouter"]
    TENANT_MODEL = "tenants.Client"
    TENANT_DOMAIN_MODEL = "tenants.Domain"
    PUBLIC_SCHEMA_URLCONF = "config.urls_public"
    SHOW_PUBLIC_IF_NO_TENANT_FOUND = True


def _default_database_context_label():
    """Human-readable DB identity for logs and startup banner."""
    db = DATABASES["default"]
    name = db.get("NAME", "")
    host = db.get("HOST", "") or ""
    port = db.get("PORT", "") or ""
    addr = f"{host}:{port}" if port else host
    if config("USE_LOCAL_POSTGRES", default=False, cast=bool):
        return f"LOCAL DEV PostgreSQL | db={name} @ {addr}"
    if config("USE_CLOUD_SQL", default=False, cast=bool):
        if host and not str(host).startswith("/cloudsql/"):
            return f"CLOUD SQL (via proxy) | db={name} @ {addr}"
        return f"CLOUD SQL (Cloud Run socket) | db={name}"
    if config("USE_SQLITE", default=False, cast=bool):
        return "SQLITE (legacy / Docker build) | db.sqlite3"
    return f"UNKNOWN | db={name}"


DATABASE_CONTEXT_LABEL = config("DATABASE_CONTEXT_LABEL", default=_default_database_context_label())

# -------------------------
# Password validation
# -------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -------------------------
# Internationalization
# -------------------------
LANGUAGE_CODE = config("LANGUAGE_CODE", default="tr")  # Turkish as default
TIME_ZONE = config("TIME_ZONE", default="Europe/Istanbul")
USE_I18N = config("USE_I18N", default=True, cast=bool)
USE_L10N = config("USE_L10N", default=True, cast=bool)
USE_TZ = config("USE_TZ", default=True, cast=bool)

LANGUAGES = [
    ("tr", _("Turkish")),
    ("en", _("English")),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

LANGUAGE_COOKIE_NAME = "django_language"
LANGUAGE_COOKIE_AGE = None
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_PATH = "/"
LANGUAGE_COOKIE_SECURE = False  # Set True in prod with HTTPS
LANGUAGE_COOKIE_HTTPONLY = False
LANGUAGE_COOKIE_SAMESITE = None

# -------------------------
# Static files
# -------------------------
STATIC_URL = config("STATIC_URL", default="/static/")
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_DIRS = []
if (BASE_DIR / "static").exists():
    STATICFILES_DIRS.append(BASE_DIR / "static")

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# -------------------------
# Media files
# -------------------------
USE_GCS = config("USE_GCS", default=False, cast=bool)  # Changed default to False

if USE_GCS:
    # Production: Use Google Cloud Storage (tenant-prefixed keys when multitenant)
    _gcs_backend = (
        "tenants.storage.TenantGCSStorage" if USE_MULTITENANT else "storages.backends.gcloud.GoogleCloudStorage"
    )
    STORAGES = {
        "default": {
            "BACKEND": _gcs_backend,
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

    # GCS Configuration
    GS_BUCKET_NAME = config("GS_BUCKET_NAME", default="carnitrack-bucket")
    GS_LOCATION = config("GS_LOCATION", default="")  # optional path prefix within bucket (e.g. "staging")
    GS_CREDENTIALS = None  # auto-detect in Cloud Run / gcloud ADC locally
    GS_PROJECT_ID = None  # auto-detect in Cloud Run

    # Critical settings to prevent signing errors
    GS_QUERYSTRING_AUTH = False  # Disable signed URLs
    GS_DEFAULT_ACL = "publicRead"  # Make files publicly readable
    GS_AUTO_CREATE_BUCKET = False
    GS_AUTO_CREATE_ACL = "publicRead"
    GS_FILE_OVERWRITE = False
    GS_EXPIRATION = None  # No URL expiration

    _media_prefix = f"{GS_LOCATION}/" if GS_LOCATION else ""
    MEDIA_URL = f"https://storage.googleapis.com/{GS_BUCKET_NAME}/{_media_prefix}"
    MEDIA_ROOT = ""
    print("☁️ Using Google Cloud Storage")

else:
    # Development: Use local file storage
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = config("MEDIA_URL", default="/media/")
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")

    # Ensure media directory exists
    os.makedirs(MEDIA_ROOT, exist_ok=True)
    print("🔧 Using local file storage")

# Remove these deprecated settings if present:
# DEFAULT_FILE_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
# -------------------------
# Other settings
# -------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "users.User"

REDIS_URL = config("REDIS_URL", default="redis://127.0.0.1:6379/0")
# If Redis is down at startup: when True, use in-process LocMemCache (dev/single-worker only).
# Default follows DEBUG so local dev tolerates stopped Redis; set False in production.
REDIS_FALLBACK_TO_LOCMEM = config("REDIS_FALLBACK_TO_LOCMEM", default=DEBUG, cast=bool)

if USE_MULTITENANT:
    # Sessions use the default cache; keys are prefixed with the current PostgreSQL schema
    # (django_tenants.cache.make_key), so public (platform admin) and each tenant stay isolated.
    _TENANT_CACHE_KEY_FN = "django_tenants.cache.make_key"
    _TENANT_CACHE_REVERSE_KEY_FN = "django_tenants.cache.reverse_key"

    from tenants.redis_support import is_redis_reachable

    _redis_up = is_redis_reachable(REDIS_URL)

    if _redis_up:
        CACHES = {
            "default": {
                "BACKEND": "django_redis.cache.RedisCache",
                "LOCATION": REDIS_URL,
                "OPTIONS": {
                    "CLIENT_CLASS": "django_redis.client.DefaultClient",
                },
                "KEY_FUNCTION": _TENANT_CACHE_KEY_FN,
                "REVERSE_KEY_FUNCTION": _TENANT_CACHE_REVERSE_KEY_FN,
            }
        }
    elif REDIS_FALLBACK_TO_LOCMEM:
        logging.getLogger(__name__).warning(
            "Redis unreachable at %s — using LocMemCache for cache/sessions. "
            "Sessions are not shared across processes (fine for runserver; do not use this mode "
            "behind multi-worker Gunicorn). Start Redis or fix REDIS_URL.",
            REDIS_URL,
        )
        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                "LOCATION": "carnitrack-mt-cache",
                "KEY_FUNCTION": _TENANT_CACHE_KEY_FN,
                "REVERSE_KEY_FUNCTION": _TENANT_CACHE_REVERSE_KEY_FN,
            }
        }
    else:
        raise ImproperlyConfigured(
            f"Redis at {REDIS_URL} is unreachable and REDIS_FALLBACK_TO_LOCMEM=False. "
            "Start Redis, set REDIS_URL, or enable REDIS_FALLBACK_TO_LOCMEM only for local debugging."
        )

    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }
    SESSION_ENGINE = "django.contrib.sessions.backends.db"

# Flash messages: session only. Default FallbackStorage also uses a signed
# ``messages`` cookie, which can fail to clear and resurface stale alerts
# (especially next to cache-backed sessions and tenant cookie domains).
MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"

# Fallback base URL (QR codes / links) when not multitenant or tenant domain unknown; also honors legacy SITE_URL env.
_SITE_URL_LEGACY = config("SITE_URL", default="")
SITE_URL_FALLBACK = config("SITE_URL_FALLBACK", default=_SITE_URL_LEGACY or "http://localhost:8000")
# TENANT_BASE_DOMAIN is resolved above (after ALLOWED_HOSTS).
# Dev: port for tenant API base URLs in email discovery (e.g. http://farm1.localhost:8000).
PUBLIC_TENANT_HTTP_PORT = config("PUBLIC_TENANT_HTTP_PORT", default="8000")
# Tenant SPA / web app (email-first login redirect target); dev often :3000, prod same host HTTPS.
PUBLIC_TENANT_WEB_HTTP_PORT = config("PUBLIC_TENANT_WEB_HTTP_PORT", default="3000")
TENANT_LOGIN_SUCCESS_REDIRECT_PATH = config("TENANT_LOGIN_SUCCESS_REDIRECT_PATH", default="/dashboard")
# When True, post-login redirect uses the same origin as api_base_url (Django :8000 in dev).
# When False (default), uses web_app_base_url (SPA :3000 in dev). Set True while templates are served from Django.
TENANT_POST_LOGIN_USE_API_HOST = config("TENANT_POST_LOGIN_USE_API_HOST", default=False, cast=bool)

# Tailwind
TAILWIND_APP_NAME = "theme"

INTERNAL_IPS = ["127.0.0.1"]

# -------------------------
# Production Security
# -------------------------
if not DEBUG:
    SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=True, cast=bool)
    SECURE_BROWSER_XSS_FILTER = config("SECURE_BROWSER_XSS_FILTER", default=True, cast=bool)
    SECURE_CONTENT_TYPE_NOSNIFF = config("SECURE_CONTENT_TYPE_NOSNIFF", default=True, cast=bool)
    SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=True, cast=bool)
    CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=True, cast=bool)
    # HSTS: off by default so operators opt in after verifying HTTPS works end-to-end.
    # Enable by setting SECURE_HSTS_SECONDS=31536000 in the production env.
    SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=0, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False, cast=bool)
    SECURE_HSTS_PRELOAD = config("SECURE_HSTS_PRELOAD", default=False, cast=bool)

    # Guard: SameSite=None is only valid when the cookie is also Secure.
    # On a non-localhost host without Secure, browsers silently downgrade to Lax,
    # breaking cross-origin session/CSRF flows in production.
    _session_ss = SESSION_COOKIE_SAMESITE  # env none → string "none" (SameSite=None on cookie)
    _csrf_ss = CSRF_COOKIE_SAMESITE
    if isinstance(_session_ss, str) and _session_ss.lower() == "none" and not SESSION_COOKIE_SECURE:
        raise ImproperlyConfigured(
            "SESSION_COOKIE_SAMESITE=none requires SESSION_COOKIE_SECURE=True in production. "
            "Browsers reject SameSite=None cookies that are not Secure outside of localhost."
        )
    if isinstance(_csrf_ss, str) and _csrf_ss.lower() == "none" and not CSRF_COOKIE_SECURE:
        raise ImproperlyConfigured(
            "CSRF_COOKIE_SAMESITE=none requires CSRF_COOKIE_SECURE=True in production. "
            "Browsers reject SameSite=None cookies that are not Secure outside of localhost."
        )

# -------------------------
# Authentication Settings
# -------------------------
LOGIN_URL = "/login/"  # Will be automatically prefixed with language by i18n_patterns
LOGIN_REDIRECT_URL = "/dashboard/"  # Default redirect after successful login
LOGOUT_REDIRECT_URL = "/logged-out/"  # Redirect after logout

if USE_MULTITENANT:
    AUTHENTICATION_BACKENDS = [
        "tenants.auth_backends.PlatformAdminBackend",
        "tenants.auth_backends.PublicSchemaSafeModelBackend",
    ]
    PLATFORM_ADMIN_LOGIN_URL = "/platform-admin/login/"
else:
    AUTHENTICATION_BACKENDS = ["django.contrib.auth.backends.ModelBackend"]


# -------------------------
# Diagnostics Report
# -------------------------
def print_settings_report():
    print("\n")
    print("*" * 62)
    print(f"*  DATABASE CONTEXT: {DATABASE_CONTEXT_LABEL}")
    print("*" * 62)
    print("\n================ Django Settings Report ================\n")

    # Debug / Environment
    print(f"🔧 DEBUG: {DEBUG}")
    print(f"🔑 SECRET_KEY: {'SET' if SECRET_KEY else 'MISSING!'}")
    print(f"🌍 ALLOWED_HOSTS: {ALLOWED_HOSTS}")
    print(f"🔒 CSRF_TRUSTED_ORIGINS: {CSRF_TRUSTED_ORIGINS}")
    print(f"🌐 SITE_URL_FALLBACK: {SITE_URL_FALLBACK}")
    if USE_MULTITENANT:
        print(f"🔴 REDIS_URL: {'SET' if REDIS_URL else 'MISSING'}")
        print(f"🏢 TENANT_BASE_DOMAIN: {TENANT_BASE_DOMAIN}")

    # Database
    db_conf = DATABASES["default"]
    print("\n📦 Database Configuration:")
    print(f"  CONTEXT: {DATABASE_CONTEXT_LABEL}")
    print(f"  ENGINE: {db_conf.get('ENGINE')}")
    print(f"  NAME:   {db_conf.get('NAME')}")
    print(f"  USER:   {db_conf.get('USER')}")
    print(f"  HOST:   {db_conf.get('HOST')}")
    print(f"  PORT:   {db_conf.get('PORT')}")

    if config("USE_CLOUD_SQL", default=False, cast=bool):
        print("  ☁️ Using Google Cloud SQL")
    elif config("USE_LOCAL_POSTGRES", default=False, cast=bool):
        print("  🐘 Using Local PostgreSQL")
    elif config("USE_SQLITE", default=False, cast=bool):
        print("  💾 Using SQLite (legacy)")
    else:
        print("  ⚠️ Database backend unknown (check USE_* flags)")

    # Storage
    print("\n🗄️ Storage Configuration:")
    if USE_GCS:
        print("  ☁️ Google Cloud Storage")
        print(f"  Bucket: {GS_BUCKET_NAME}")
        print(f"  Media URL: {MEDIA_URL}")
    else:
        print("  📂 Local File Storage")
        print(f"  Media Root: {MEDIA_ROOT}")
        print(f"  Media URL: {MEDIA_URL}")

    # Localization
    print("\n🌐 Localization:")
    print(f"  LANGUAGE_CODE: {LANGUAGE_CODE}")
    print(f"  TIME_ZONE: {TIME_ZONE}")
    print(f"  USE_I18N: {USE_I18N}")
    print(f"  USE_TZ: {USE_TZ}")

    # Printer Settings (per-tenant via Client.printer_turkish_mode)
    print("\n🖨️ Printer Settings: configured per-tenant (Client.printer_turkish_mode)")

    # Logging & Security
    print("\n🔐 Security:")
    print(f"  SESSION_COOKIE_SECURE: {config('SESSION_COOKIE_SECURE', default=False, cast=bool)}")
    print(f"  CSRF_COOKIE_SECURE: {config('CSRF_COOKIE_SECURE', default=False, cast=bool)}")
    print(f"  SECURE_SSL_REDIRECT: {config('SECURE_SSL_REDIRECT', default=False, cast=bool)}")

    print("\n========================================================\n")


# Call report when settings are loaded
print_settings_report()

# One line on stderr as soon as settings load (visible before Django configures LOGGING)
logging.getLogger("carnitrack.database").warning(
    "DATABASE CONTEXT — %s",
    DATABASE_CONTEXT_LABEL,
)