"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

from pathlib import Path
import os
from decouple import config, Csv
import dj_database_url
from django.utils.translation import gettext_lazy as _

DEFAULT_FILE_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', cast=Csv())

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_fsm',
    'tailwind',        # Django Tailwind
    'widget_tweaks',   # Form tweaks in templates

    # Local Apps
    'users',
    'reception',
    'processing',
    'inventory',
    'portal',
    'core',
    'labeling',
    'reporting',
    'theme',           # Tailwind theme app
]

INSTALLED_APPS += ['storages']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',   # i18n
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# -------------------------
# Database Configuration
# -------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Cloud SQL
if config('USE_CLOUD_SQL', default=False, cast=bool):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': f'/cloudsql/{config("CLOUD_SQL_CONNECTION_NAME")}',  # socket path
        'PORT': '',
    }

# Local Postgres
elif config('USE_LOCAL_POSTGRES', default=False, cast=bool):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='carnitrack_local'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5433'),
    }

# -------------------------
# Password validation
# -------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# -------------------------
# Internationalization
# -------------------------
LANGUAGE_CODE = config('LANGUAGE_CODE', default='tr')  # Turkish as default
TIME_ZONE = config('TIME_ZONE', default='Europe/Istanbul')
USE_I18N = config('USE_I18N', default=True, cast=bool)
USE_L10N = config('USE_L10N', default=True, cast=bool)
USE_TZ = config('USE_TZ', default=True, cast=bool)

LANGUAGES = [
    ('tr', _('Turkish')),
    ('en', _('English')),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = None
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_PATH = '/'
LANGUAGE_COOKIE_SECURE = False  # Set True in prod with HTTPS
LANGUAGE_COOKIE_HTTPONLY = False
LANGUAGE_COOKIE_SAMESITE = None

"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

from pathlib import Path
import os
from decouple import config, Csv
import dj_database_url
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', cast=Csv())

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_fsm',
    'tailwind',        # Django Tailwind
    'widget_tweaks',   # Form tweaks in templates

    # Local Apps
    'users',
    'reception',
    'processing',
    'inventory',
    'portal',
    'core',
    'labeling',
    'reporting',
    'theme',           # Tailwind theme app
]

INSTALLED_APPS += ['storages']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',   # i18n
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# -------------------------
# Database Configuration
# -------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Cloud SQL
if config('USE_CLOUD_SQL', default=False, cast=bool):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': f'/cloudsql/{config("CLOUD_SQL_CONNECTION_NAME")}',  # socket path
        'PORT': '',
    }

# Local Postgres
elif config('USE_LOCAL_POSTGRES', default=False, cast=bool):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='carnitrack_local'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5433'),
    }

# -------------------------
# Password validation
# -------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# -------------------------
# Internationalization
# -------------------------
LANGUAGE_CODE = config('LANGUAGE_CODE', default='tr')  # Turkish as default
TIME_ZONE = config('TIME_ZONE', default='Europe/Istanbul')
USE_I18N = config('USE_I18N', default=True, cast=bool)
USE_L10N = config('USE_L10N', default=True, cast=bool)
USE_TZ = config('USE_TZ', default=True, cast=bool)

LANGUAGES = [
    ('tr', _('Turkish')),
    ('en', _('English')),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = None
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_PATH = '/'
LANGUAGE_COOKIE_SECURE = False  # Set True in prod with HTTPS
LANGUAGE_COOKIE_HTTPONLY = False
LANGUAGE_COOKIE_SAMESITE = None

# -------------------------
# Static files
# -------------------------
STATIC_URL = config('STATIC_URL', default='/static/')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = []
if (BASE_DIR / 'static').exists():
    STATICFILES_DIRS.append(BASE_DIR / 'static')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# -------------------------
# Media files
# -------------------------
USE_GCS = config("USE_GCS", default=False, cast=bool)  # Changed default to False

if USE_GCS:
    # Production: Use Google Cloud Storage
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    
    # GCS Configuration
    GS_BUCKET_NAME = config("GS_BUCKET_NAME", default="carnitrack-bucket")
    GS_CREDENTIALS = None  # auto-detect in Cloud Run
    GS_PROJECT_ID = None   # auto-detect in Cloud Run
    
    # Critical settings to prevent signing errors
    GS_QUERYSTRING_AUTH = False  # Disable signed URLs
    GS_DEFAULT_ACL = 'publicRead'  # Make files publicly readable
    GS_AUTO_CREATE_BUCKET = False
    GS_AUTO_CREATE_ACL = 'publicRead'
    GS_FILE_OVERWRITE = False
    GS_EXPIRATION = None  # No URL expiration
    
    MEDIA_URL = f"https://storage.googleapis.com/{GS_BUCKET_NAME}/"
    MEDIA_ROOT = ""
    print("☁️ Using Google Cloud Storage")

else:
    # Development: Use local file storage
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = config("MEDIA_URL", default="/media/")
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
    
    # Ensure media directory exists
    os.makedirs(MEDIA_ROOT, exist_ok=True)
    print("🔧 Using local file storage")

# Remove these deprecated settings if present:
# DEFAULT_FILE_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
# -------------------------
# Other settings
# -------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.User'

# Site URL for QR codes and external links
SITE_URL = config('SITE_URL', default='https://carnitrack-app-1000671720976.europe-west1.run.app')

# Company Information for Labels
COMPANY_NAME = config('COMPANY_NAME', default='POMET ET  VE')
COMPANY_FULL_NAME = config('COMPANY_FULL_NAME', default='ET ÜRÜNLERİ LTD. ŞTİ.')
COMPANY_ADDRESS = config('COMPANY_ADDRESS', default='Lapseki / ÇANAKKALE')
LICENSE_NO = config('LICENSE_NO', default='17-0509')
OPERATION_NO = config('OPERATION_NO', default='TR17 12345678')

# Printer Settings
PRINTER_TURKISH_MODE = config('PRINTER_TURKISH_MODE', default='unicode')  # 'unicode', 'ascii', or 'codepage1254'

# Tailwind
TAILWIND_APP_NAME = 'theme'

INTERNAL_IPS = ["127.0.0.1"]

# -------------------------
# Production Security
# -------------------------
if not DEBUG:
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SECURE_BROWSER_XSS_FILTER = config('SECURE_BROWSER_XSS_FILTER', default=True, cast=bool)
    SECURE_CONTENT_TYPE_NOSNIFF = config('SECURE_CONTENT_TYPE_NOSNIFF', default=True, cast=bool)
    SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=bool)
    CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)

# -------------------------
# Other settings
# -------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.User'

# Tailwind
TAILWIND_APP_NAME = 'theme'

INTERNAL_IPS = ["127.0.0.1"]

# -------------------------
# Diagnostics Report
# -------------------------
def print_settings_report():
    print("\n================ Django Settings Report ================\n")

    # Debug / Environment
    print(f"🔧 DEBUG: {DEBUG}")
    print(f"🔑 SECRET_KEY: {'SET' if SECRET_KEY else 'MISSING!'}")
    print(f"🌍 ALLOWED_HOSTS: {ALLOWED_HOSTS}")
    print(f"🔒 CSRF_TRUSTED_ORIGINS: {CSRF_TRUSTED_ORIGINS}")
    print(f"🌐 SITE_URL: {SITE_URL}")

    # Database
    db_conf = DATABASES["default"]
    print("\n📦 Database Configuration:")
    print(f"  ENGINE: {db_conf.get('ENGINE')}")
    print(f"  NAME:   {db_conf.get('NAME')}")
    print(f"  USER:   {db_conf.get('USER')}")
    print(f"  HOST:   {db_conf.get('HOST')}")
    print(f"  PORT:   {db_conf.get('PORT')}")

    if config("USE_CLOUD_SQL", default=False, cast=bool):
        print("  ☁️ Using Google Cloud SQL")
    elif config("USE_LOCAL_POSTGRES", default=False, cast=bool):
        print("  🐘 Using Local PostgreSQL")
    else:
        print("  💾 Using SQLite (default)")

    # Storage
    print("\n🗄️ Storage Configuration:")
    if USE_GCS:
        print(f"  ☁️ Google Cloud Storage")
        print(f"  Bucket: {GS_BUCKET_NAME}")
        print(f"  Media URL: {MEDIA_URL}")
    else:
        print("  📂 Local File Storage")
        print(f"  Media Root: {MEDIA_ROOT}")
        print(f"  Media URL: {MEDIA_URL}")

    # Localization
    print("\n🌐 Localization:")
    print(f"  LANGUAGE_CODE: {LANGUAGE_CODE}")
    print(f"  TIME_ZONE: {TIME_ZONE}")
    print(f"  USE_I18N: {USE_I18N}")
    print(f"  USE_TZ: {USE_TZ}")

    # Company Information
    print("\n🏢 Company Information:")
    print(f"  COMPANY_NAME: {COMPANY_NAME}")
    print(f"  COMPANY_FULL_NAME: {COMPANY_FULL_NAME}")
    print(f"  COMPANY_ADDRESS: {COMPANY_ADDRESS}")
    print(f"  LICENSE_NO: {LICENSE_NO}")
    print(f"  OPERATION_NO: {OPERATION_NO}")

    # Printer Settings
    print("\n🖨️ Printer Settings:")
    print(f"  TURKISH_CHARACTER_MODE: {PRINTER_TURKISH_MODE}")

    # Logging & Security
    print("\n🔐 Security:")
    print(f"  SESSION_COOKIE_SECURE: {config('SESSION_COOKIE_SECURE', default=False, cast=bool)}")
    print(f"  CSRF_COOKIE_SECURE: {config('CSRF_COOKIE_SECURE', default=False, cast=bool)}")
    print(f"  SECURE_SSL_REDIRECT: {config('SECURE_SSL_REDIRECT', default=False, cast=bool)}")

    print("\n========================================================\n")


# Call report when settings are loaded
print_settings_report()
