"""
Turkish provinces (il) by vehicle registration code (plaka) and VD label abbreviations for printers.

VD_LABEL_ABBREV_BY_PLAKA values are ASCII tokens printed before " VD: " on meat labels. They must match
operational / regulatory expectations; changing this map is a compliance-sensitive edit.
"""

from __future__ import annotations

# (plaka, display name TR) — ordered 01 … 81
PROVINCE_CHOICES: tuple[tuple[str, str], ...] = (
    ("01", "Adana"),
    ("02", "Adıyaman"),
    ("03", "Afyonkarahisar"),
    ("04", "Ağrı"),
    ("05", "Amasya"),
    ("06", "Ankara"),
    ("07", "Antalya"),
    ("08", "Artvin"),
    ("09", "Aydın"),
    ("10", "Balıkesir"),
    ("11", "Bilecik"),
    ("12", "Bingöl"),
    ("13", "Bitlis"),
    ("14", "Bolu"),
    ("15", "Burdur"),
    ("16", "Bursa"),
    ("17", "Çanakkale"),
    ("18", "Çankırı"),
    ("19", "Çorum"),
    ("20", "Denizli"),
    ("21", "Diyarbakır"),
    ("22", "Edirne"),
    ("23", "Elazığ"),
    ("24", "Erzincan"),
    ("25", "Erzurum"),
    ("26", "Eskişehir"),
    ("27", "Gaziantep"),
    ("28", "Giresun"),
    ("29", "Gümüşhane"),
    ("30", "Hakkari"),
    ("31", "Hatay"),
    ("32", "Isparta"),
    ("33", "Mersin"),
    ("34", "İstanbul"),
    ("35", "İzmir"),
    ("36", "Kars"),
    ("37", "Kastamonu"),
    ("38", "Kayseri"),
    ("39", "Kırklareli"),
    ("40", "Kırşehir"),
    ("41", "Kocaeli"),
    ("42", "Konya"),
    ("43", "Kütahya"),
    ("44", "Malatya"),
    ("45", "Manisa"),
    ("46", "Kahramanmaraş"),
    ("47", "Mardin"),
    ("48", "Muğla"),
    ("49", "Muş"),
    ("50", "Nevşehir"),
    ("51", "Niğde"),
    ("52", "Ordu"),
    ("53", "Rize"),
    ("54", "Sakarya"),
    ("55", "Samsun"),
    ("56", "Siirt"),
    ("57", "Sinop"),
    ("58", "Sivas"),
    ("59", "Tekirdağ"),
    ("60", "Tokat"),
    ("61", "Trabzon"),
    ("62", "Tunceli"),
    ("63", "Şanlıurfa"),
    ("64", "Uşak"),
    ("65", "Van"),
    ("66", "Yozgat"),
    ("67", "Zonguldak"),
    ("68", "Aksaray"),
    ("69", "Bayburt"),
    ("70", "Karaman"),
    ("71", "Kırıkkale"),
    ("72", "Batman"),
    ("73", "Şırnak"),
    ("74", "Bartın"),
    ("75", "Ardahan"),
    ("76", "Iğdır"),
    ("77", "Yalova"),
    ("78", "Karabük"),
    ("79", "Kilis"),
    ("80", "Osmaniye"),
    ("81", "Düzce"),
)

# Exact ASCII prefix before " VD: " on ZPL — one entry per plaka (sensitive for compliance).
VD_LABEL_ABBREV_BY_PLAKA: dict[str, str] = {
    "01": "ADANA",
    "02": "ADIYAMAN",
    "03": "AFYON",
    "04": "AGRI",
    "05": "AMASYA",
    "06": "ANKARA",
    "07": "ANTALYA",
    "08": "ARTVIN",
    "09": "AYDIN",
    "10": "BALIKESIR",
    "11": "BILECIK",
    "12": "BINGOL",
    "13": "BITLIS",
    "14": "BOLU",
    "15": "BURDUR",
    "16": "BURSA",
    "17": "CKALE",
    "18": "CANKIRI",
    "19": "CORUM",
    "20": "DENIZLI",
    "21": "DIYARBAKIR",
    "22": "EDIRNE",
    "23": "ELAZIG",
    "24": "ERZINCAN",
    "25": "ERZURUM",
    "26": "ESKISEHIR",
    "27": "GAZIANTEP",
    "28": "GIRESUN",
    "29": "GUMUSHANE",
    "30": "HAKKARI",
    "31": "HATAY",
    "32": "ISPARTA",
    "33": "MERSIN",
    "34": "ISTANBUL",
    "35": "IZMIR",
    "36": "KARS",
    "37": "KASTAMONU",
    "38": "KAYSERI",
    "39": "KIRKLARELI",
    "40": "KIRSEHIR",
    "41": "KOCAELI",
    "42": "KONYA",
    "43": "KUTAHYA",
    "44": "MALATYA",
    "45": "MANISA",
    "46": "KAHRAMANMARAS",
    "47": "MARDIN",
    "48": "MUGLA",
    "49": "MUS",
    "50": "NEVSEHIR",
    "51": "NIGDE",
    "52": "ORDU",
    "53": "RIZE",
    "54": "SAKARYA",
    "55": "SAMSUN",
    "56": "SIIRT",
    "57": "SINOP",
    "58": "SIVAS",
    "59": "TEKIRDAG",
    "60": "TOKAT",
    "61": "TRABZON",
    "62": "TUNCELI",
    "63": "SANLIURFA",
    "64": "USAK",
    "65": "VAN",
    "66": "YOZGAT",
    "67": "ZONGULDAK",
    "68": "AKSARAY",
    "69": "BAYBURT",
    "70": "KARAMAN",
    "71": "KIRIKKALE",
    "72": "BATMAN",
    "73": "SIRNAK",
    "74": "BARTIN",
    "75": "ARDAHAN",
    "76": "IGDIR",
    "77": "YALOVA",
    "78": "KARABUK",
    "79": "KILIS",
    "80": "OSMANIYE",
    "81": "DUZCE",
}

_DEFAULT_FALLBACK_PREFIX = "CKALE"


def get_vd_label_prefix_for_plaka(plaka: str | None) -> str:
    """Return the printer VD line prefix for a plaka, or a safe default if unknown."""
    if not plaka:
        return _DEFAULT_FALLBACK_PREFIX
    key = str(plaka).strip().zfill(2)
    return VD_LABEL_ABBREV_BY_PLAKA.get(key, _DEFAULT_FALLBACK_PREFIX)
